apiVersion: apps/v1
kind: Deployment
metadata:
  name: edittime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edittime
  template:
    metadata:
      labels:
        app: edittime
    spec:
      containers: 
      - name: edittime
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/edittime:$VERSION
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
        - name: STORAGE_ACCOUNT_NAME
          value: $STORAGE_ACCOUNT_NAME
        - name: STORAGE_ACCESS_KEY
          value: $STORAGE_ACCESS_KEY
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: edittime
spec:
  selector:
    app: edittime
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cpu-edittime
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edittime
  metrics:
  - type: Resource
    resource:
      name: edittime-cpu #this is for cpu usage
      target:
        type: Utilization
        averageUtilization: 50 #The average utilization of the cpu in the application container of all the pods is 50%
  - type: Resource
    resource:
      name: edittime-memory #this is for memory usage
      target:
        type: AverageValue
        averageValue: 192Mi #The average utilization of the memory in the application container of all the pods is 75%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15

      nodePort: 31000